name: coloring_pages
version: 0.1.0
publish_to: 'none'
description: Cross-platform coloring page generator.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path_provider: ^2.1.3
  open_filex: ^4.3.2
  flutter_spinkit: ^5.2.0

flutter:
  uses-material-design: true
